name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World
  allowed-ip:
    description: allowed ip list
    default: 8.8.8.8
    required: true
  allowed-hosts:
    description: allowed host list
    default: "kondukto.io"
    required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
